# name: Test Environment Variables

# on:
#   push:
#     branches:
#       - main 

# jobs:
#   test-env:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Copy .env file from server
#       uses: appleboy/scp-action@master
#       with:
#         host: ${{ secrets.SERVER_HOST }}
#         username: ${{ secrets.SERVER_USER }}
#         port: ${{ secrets.SERVER_PORT }}
#         key: ${{ secrets.SERVER_SSH_KEY }}
#         source: "/home/web/thecacao.com.tr/production/.env"
#         target: "./.env"
#         tar_exec: ""

#     - name: Apply environment variables and print
#       run: |
#         export $(cat ./.env | xargs)
#         echo $NEXT_PUBLIC_API_URL  # Test için belirli bir environment değişkenini ekrana yazdır
