name: Test Environment Variables

on:
  push:
    branches:
      - main  # Yalnızca 'main' branch'e push yapıldığında çalışacak

jobs:
  test-env:
    runs-on: ubuntu-latest

    steps:
    # Kodu klonla
    - name: Checkout code
      uses: actions/checkout@v2

    # Sunucudan .env dosyasını kopyala
    - name: Fetch .env file from server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        port: ${{ secrets.SERVER_PORT }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "/home/web/thecacao.com.tr/production/.env"
        target: "./.env"

    # Ortam değişkenini yükle ve ekrana yazdır
    - name: Apply environment variables and print
      run: |
        export $(cat ./.env | xargs)
        echo $NEXT_PUBLIC_API_URL  # Test için belirli bir environment değişkenini ekrana yazdır
