name: Deploy to Production

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy .env file from server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        port: ${{ secrets.SERVER_PORT }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "/home/web/thecacao.com.tr/production/.env"
        target: "/home/runner/work/thecacao-server/thecacao-server/.env"

    - name: Load environment variables
      run: |
        export $(cat /home/runner/work/thecacao-server/thecacao-server/.env | xargs)
        echo $NEXT_PUBLIC_API_URL

    - name: Install Nx CLI
      run: npm install -g nx

    - name: Install dependencies
      run: npm install

    - name: Build project with server .env
      run: |
        nx build www

    - name: Copy build and necessary files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        port: ${{ secrets.SERVER_PORT }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "apps/www/.next/**, apps/www/package.json" 
        target: "/home/web/thecacao.com.tr/production"

    - name: Run build commands on server
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        port: ${{ secrets.SERVER_PORT }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/web/thecacao.com.tr/production
          npm install
          # redis-cli FLUSHALL
          # rm -rf /var/cache/nginx/*
          # nginx -s reload
